FROM nginx:alpine

# Copy website files
COPY index.html /usr/share/nginx/html/index.html

# Copy custom Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]